#!/bin/bash

CURRDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" #TODO BASH_SOURCE[0]?
source ${CURRDIR}/setup.inc

function Log {
	#  TAG=$1
	#  MSG=$2
	#  ERR=$3
	if [ $3 -eq 1 ]; then
		logger -s "[OpenKarotz] [ERROR]" "$1 $2" &>/dev/null
	else
		logger "[OpenKarotz]" "$1 $2" &>/dev/null
	fi
}

if [ ! -d ${SOURCES_CNF} ]; then
	Log "[Install]" "${SOURCES_CNF} not found." 1
	exit 1
fi
if [ ! -d ${SOURCES_TDIR} ]; then
	Log "[Install]" "${SOURCES_TDIR} not found." 1
	exit 1
fi
echo "SOURCES_TDIR: ${SOURCES_TDIR}"
echo "SOURCES_CNF: ${SOURCES_CNF}"

Log "[Install]" "CleanUP"
if [ -d ${TDIR} ]; then
	Log "[Install]" "Removing directory: ${TDIR}"
	rm -fr ${TDIR} &>/dev/null
	Log "[Install]" "Result: $?"
fi
if [ ! -d ${CNF_DATADIR} ]; then
	Log "[Install]" "Creating Empty Dir: ${CNF_DATADIR}"
	mkdir -p ${CNF_DATADIR}
	Log "[Install]" "Result: $?"
fi

Log "[Install]" "Copy"
Log "[Install]" "Creating directory: ${CNF_DATADIR}"
cp -fR ${SOURCES_CNF}/* ${CNF_DATADIR}/ &>/dev/null
Log "[Install]" "Result: $?"
Log "[Install]" "Creating directory: ${TDIR}"
cp -fR ${SOURCES_TDIR}/ ${TDIR}/ &>/dev/null
Log "[Install]" "Result: $?"
Log "[Install]" "Creating Links"
ln -s ${CNF_DATADIR}/Snapshots ${TDIR}/snapshots &>/dev/null
ln -s ${CNF_DATADIR}/Tmp ${TDIR}/tts_cache &>/dev/null
Log "[Install]" "Managing Rights"
chmod -R 755 ${TDIR}

echo "----------------------------------------"
echo Done
echo You must now manually Download Apps
echo from Update Tab
echo "----------------------------------------"

Log "[Install]" "Finished"
