#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/url.inc

ReadUrlParams
L=${URLParam[url]:-${1:-${CNF_ROOT_URL}}}

R=$(curl -w "%{http_code}" -s -L -k -o /tmp/curlout "${L}")
if [ ${R} -eq 200 ]; then
	DT=$(cat /tmp/curlout 2>/dev/null)
	rm -f /tmp/curlout
else
	DT='{"return":"1","msg":"Error reading file."}'
fi
SendResponse "${DT}"
