#!/bin/bash

#TODO Should use APP param + this script is not used by any other script -> should we keep it?

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

CheckIsNotSleeping

ReadUrlParams
APP=${URLParam[app]}
CheckMandatoryParameter "${APP}" app

CheckMandatoryDirectory "${CNF_DATADIR}/Apps"
CheckMandatoryDirectory "${CNF_DATADIR}/Apps/Clock"
CheckMandatoryDirectory "${CNF_DATADIR}/Apps/Clock/Data"
#TODO check other apps?

KillProcess

SendResponse "${AL}" #TODO ${AL}?
