#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

AL='{ "return":"0", "apps": [
{ "id":"moods","file":"apps.moods.install" },
{ "id":"funny clock","file":"apps.clock.install" },
{ "id":"radio","file":"apps.radio.install" },
{ "id":"story","file":"apps.story.install" },
{ "id":"story-Berceuse","file":"apps.story1.install" },
{ "id":"story-Contes","file":"apps.story2.install" },
{ "id":"story-Histoires","file":"apps.story3.install" }
] }'
SendResponse "${AL}"
