#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/leds.inc

#TODO Why is it done only when Karotz is awake?
if [ ! -e "${CNF_DATADIR}/Run/karotz.sleep" ]; then
	if ping 8.8.8.8 -c 3 -q &>/dev/null; then
		LedsRestore
		Log "[System]" "Check Network Health - OK"
	else
		Log "[System]" "Lost Network connexion" 1
		Leds ${RED} ${BLUE} 1 1 100
		Log "[System]" "Check Network Health - Reboot" 1
		/sbin/reboot
	fi
fi
