#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

ReadUrlParams
ID=${URLParam[id]}

if [ -z "${ID}" ]; then
	rm -rf ${CNF_DATADIR}/Tmp/*.mp3 &>/dev/null
	rm -rf ${CNF_DATADIR}/Tmp/*.voice &>/dev/null
	rm -rf ${CNF_DATADIR}/Tmp/*.txt &>/dev/null
	Log "[TTS]" "TTS cache cleared"
	DATA='{"return":"0","msg":"TTS cache cleared."}'
else
	if [ ! -e "${CNF_DATADIR}/Tmp/${ID}.mp3" ]; then
		Log "[TTS]" "Cache file not found: "${ID} 1
		DATA='{"return":"1","msg":"TTS cache file not found."}'
	else
		rm -rf ${CNF_DATADIR}/Tmp/${ID}.* &>/dev/null
		Log "[TTS]" "Cache files cleared: "${ID}
		DATA='{"return":"0","msg":"TTS cache files cleared.","id":"'${ID}'."}'
	fi
fi
SendResponse "${DATA}"
