#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

rm -rf ${CNF_DATADIR}/Snapshots/* &>/dev/null
Log "[Snapshot]" "Snapshots cleared"
DATA='{"return":"0","msg":"Snapshots cleared."}'
SendResponse "${DATA}"
