#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

CDIR="/www/cgi-bin"
CheckMandatoryDirectory ${CDIR}

chmod -R u=rwX,go=rX /www &>/dev/null
find ${CDIR} \! \( -name \*.bak -o -name \*.BAKUP\* \) -exec chmod ugo+x {} \; &>/dev/null
Log "[System]" "Permissions set to /www/ and childen folders"
DATA='{"return":"0"}'
SendResponse "${DATA}"
