#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/ears.inc
source /www/cgi-bin/leds.inc
source /www/cgi-bin/rfid.inc

function LOG {
	logger "DBUSEVENTS $1"
}

RFID_DETECTED=0
SOUND="twang_04.mp3"
dbus-monitor --system | while read -r line 2>/dev/null; do
	# Exclude Common DBUS messages if not in RFID catching
	if [ ${RFID_DETECTED} -eq 0 ]; then
		if echo ${line} | grep '^string "\|^int32 '; then
			LOG "LINE EXCLUDED IS: [${line}] / RFID_DETECTED = [${RFID_DETECTED}]"
			continue
		else
			LOG "LINE TO PARSE IS: [${line}] / RFID_DETECTED = [${RFID_DETECTED}]"
		fi
	fi

	if echo ${line} | grep 'member=lclick_start\|member=click\|member=dclick\|member=tclick'; then
		#LOG "Click event"
		#echo "===>"${line}
		# ---------------------
		# BUTTON HANLDER
		# DBUS
		# ---------------------
		# Long Button Press Detected
		# Start or stop Tag Recording
		# ---------------------
		if echo ${line} | grep "member=lclick_start"; then
			KillProcess
			if [ -e "${CNF_DATADIR}/Run/rfid.record" ]; then
				StopTagRecording
				LOG "StopTagRecording"
			else
				Leds ${PINK} ${BLACK} 1 1
				StartTagRecording
				LOG "StartTagRecording"
			fi
			continue
		fi
		# ---------------------
		# Single Click  Detected
		# User Defined Action
		# ---------------------
		if echo ${line} | grep "member=click"; then
			LOG "simple click"
			PlaySound "${CNF_DATADIR}/Sounds/${SOUND}"
			continue
		fi
		# ---------------------
		# Double Click
		# User Defined Action
		# ---------------------
		if echo ${line} | grep "member=dclick"; then
			LOG "double click"
			EarsReset
			KillProcess
			LedsRestore
			#PlaySound "${CNF_DATADIR}/Sounds/${SOUND}"
			continue
		fi
		# ---------------------
		# Triple Click
		# PreDefined Action
		# ---------------------
		if echo ${line} | grep "member=tclick"; then
			LOG "triple click"
			#PlaySound ${CNF_DATADIR}/Sounds/flush.mp3
			#/sbin/reboot
			continue
		fi
	fi
	# ---------------------
	# RFID HANDLER
	# DBUS
	# ---------------------
	# Process Tag Action
	# ---------------------
	if [ ${RFID_DETECTED} -eq 7 ]; then
		LOG "RFID HANDLER"
		# Record Tag
		if [ -e "${CNF_DATADIR}/Run/rfid.record" ]; then
			if [ -e "${CNF_DATADIR}/Rfid/${RFID_ID}.rfid" ]; then
				PlaySound ${CNF_DATADIR}/Sounds/rfid_error.mp3
				PlaySound ${CNF_DATADIR}/Voice/Rfid_objet_deja_enregistre.mp3
			else
				echo "" >${CNF_DATADIR}/Rfid/${RFID_ID}.rfid
				echo ${RFID_COLOR} >${CNF_DATADIR}/Rfid/${RFID_ID}.color
				echo ${RFID_TYPE} >${CNF_DATADIR}/Rfid/${RFID_ID}.type
				PlaySound ${CNF_DATADIR}/Sounds/rfid_ok.mp3
				PlaySound ${CNF_DATADIR}/Voice/Rfid_objet_enregistre.mp3
			fi
		# Delete Tag
		elif [ -e "${CNF_DATADIR}/Run/rfid.delete" ]; then
			Playsound ${CNF_DATADIR}/Voice/Rfid_objet_supprime.mp3
			rm -f ${CNF_DATADIR}/Rfid/${RFID_ID}.*
		# Execute Tag
		else
			echo "${CNF_DATADIR}/Rfid/${RFID_ID}.rfid"
			if [ ! -e "${CNF_DATADIR}/Rfid/${RFID_ID}.rfid" ]; then
				if [ ! -e "${CNF_DATADIR}/Run/karotz.sleep" ]; then
					PlaySound ${CNF_DATADIR}/Sounds/rfid_error.mp3
					PlaySound ${CNF_DATADIR}/Voice/Rfid_Object_inconnu.mp3
				fi
			else
				if [ ! -e "${CNF_DATADIR}/Rfid/${RFID_ID}.action" ]; then
					if [ ! -e "${CNF_DATADIR}/Run/karotz.sleep" ]; then
						PlaySound ${CNF_DATADIR}/Sounds/rfid_error.mp3
						PlaySound ${CNF_DATADIR}/Voice/Rfid_objet_pas_action.mp3
					fi
				else
					Leds ${RED} ${BLACK} 0 1
					if [ ! -e "${CNF_DATADIR}/Run/karotz.sleep" ]; then
						PlaySound ${CNF_DATADIR}/Sounds/${SOUND}
					fi
					SCENE_ID=$(cat ${CNF_DATADIR}/Rfid/${RFID_ID}.rfid) #TODO usefull?
					SCENE_CMD=$(cat ${CNF_DATADIR}/Rfid/${RFID_ID}.cmd)
					LOG "Calling external action: $(GetCmdName ${SCENE_CMD})"
					LedsRestore
					eval "$(cat ${CNF_DATADIR}/Rfid/${RFID_ID}.action | busybox base64 -d)"
				fi
			fi
		fi
		RFID_DETECTED=0
		continue
	fi
	# ---------------------
	# Read Color
	# ---------------------
	if [ ${RFID_DETECTED} -eq 6 ]; then
		LOG "Read Color"
		RFID_COLOR=$(awk -F\  '{print $2}' <<<"${line}")
		#echo "Color==>"${RFID_COLOR}"<=="
		RFID_DETECTED=7
		continue
	fi
	# ---------------------
	# Discard Picture
	# ---------------------
	if [ ${RFID_DETECTED} -eq 5 ]; then
		LOG "Discard Picture"
		#echo "Picture==>"${line}
		RFID_DETECTED=6
		continue
	fi
	# ---------------------
	# Read Type
	# ---------------------
	if [ ${RFID_DETECTED} -eq 4 ]; then
		LOG "Read Type"
		RFID_TYPE=$(awk -F\ '{print $2}' <<<"${line}")
		GetRfidTypeName ${RFID_TYPE}
		RFID_DETECTED=5
		continue
	fi
	# ---------------------
	# Discard App
	# ---------------------
	if [ ${RFID_DETECTED} -eq 3 ]; then
		LOG "Discard App"
		#echo "App==>"${line}
		RFID_DETECTED=4
		continue
	fi
	# ---------------------
	# Discard Flag
	# ---------------------
	if [ ${RFID_DETECTED} -eq 2 ]; then
		LOG "Discard Flash"
		#echo "Flag==>"${line}
		RFID_DETECTED=3
		continue
	fi
	# ---------------------
	# Read TAG ID
	# ---------------------
	if [ ${RFID_DETECTED} -eq 1 ]; then
		LOG "Read TAG ID"

		RFID_ID=$(awk -F\" '{print $2}' <<<"${line}")
		#echo "ID ==>"${RFID_ID}"<=="
		if [ -e "${CNF_DATADIR}/Run/rfid.record" ]; then
			RFID_DETECTED=2
		else
			RFID_DETECTED=7

		fi
		continue
		#PlaySound ${CNF_DATADIR}/Sounds/rfid_ok.mp3
	fi
	# ---------------------
	# Tag Detected
	# ---------------------
	if echo ${line} | grep 'member=tag_in'; then
		LOG "Tag Detected IN"
		RFID_DETECTED=1
		continue
	fi
	if echo ${line} | grep 'member=tag_out'; then
		LOG "Tag Detected OUT"
		continue
	fi

done
