#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

CL=""
while read -r f; do
	ID=$(echo ${f} | cut -d '/' -f 5 | cut -d '.' -f 1)
	VOICE="unknown"
	if [ -e ${CNF_DATADIR}/Tmp/${ID}".voice" ]; then
		VOICE=$(cat ${CNF_DATADIR}/Tmp/${ID}".voice")
	fi
	TEXT=$(cat "${f}" | sed -r 's/["]+/ /g')
	CL=${CL}'{"id":"'${ID}'","text":"'${TEXT}'","voice":"'${VOICE}'"},'
done < <(find ${CNF_DATADIR}/Tmp/ -type f -name '*.txt')
DATA='{"return":"0","cache":['${CL%?}']}'
SendResponse "${DATA}"
