#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/ears.inc

CheckIsNotSleeping
CheckEarsNotDisabled
KillProcess

EarsReset
Log "[Ears]" "Ears position reset"
DATA='{"return":"0","msg":"Ears position reset."}'
SendResponse "${DATA}"
