#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/ears.inc

CheckIsNotSleeping
CheckEarsNotDisabled

ReadUrlParams
L=${URLParam[left]}
R=${URLParam[right]}
NO_RESET=${URLParam[noreset]:-0}
CheckMandatoryParameter "${L}" left
CheckMandatoryParameter "${R}" right

if [ ${NO_RESET} -ne 1 ]; then
	Log "[Ears]" "Reset ears position"
	EarsReset
fi
EarsMove ${R} ${L} 100
Log "[Ears]" "Ears moved, left position: ${L}, right position: ${R}"
DATA='{"return":"0","left":"'${L}'","right":"'${R}'"}'
SendResponse "${DATA}"
