#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/ears.inc

#TODO Why not calling cgi-bin/ears with the random positions?
CheckIsNotSleeping
CheckEarsNotDisabled

ReadUrlParams
NO_RESET=${URLParam[noreset]:-0}

if [ ${NO_RESET} -ne 1 ]; then
	Log "[Ears]" "Reset ears position"
	EarsReset
fi
L=$((RANDOM % 15))
R=$((RANDOM % 15))
EarsMove ${L} ${R} 100
Log "[Ears]" "Ears are moving, left position: ${L}, right position: ${R}"
DATA='{"return":"0","left":"'${L}'","right":"'${R}'"}'
SendResponse "${DATA}"
