#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/ears.inc

ReadUrlParams
D=${URLParam[disable]:-0}

if [ ${D} -eq 1 ]; then
	echo "1" >${CNF_DATADIR}/Run/ears.disabled
	Log "[Ears]" "Ears disabled"
	DATA='{"return":"0","disabled":"1"}'
else
	rm -f ${CNF_DATADIR}/Run/ears.disabled &>/dev/null
	EarsReset
	Log "[Ears]" "Ears enabled"
	DATA='{"return":"0","disabled":"0"}'
fi
SendResponse "${DATA}"
