#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

EEDOMUS_USER=""
if [ -e "${CNF_DATADIR}/Run/eedomus.user" ]; then
	EEDOMUS_USER=$(cat ${CNF_DATADIR}/Run/eedomus.user)
fi
EEDOMUS_PASS=""
if [ -e "${CNF_DATADIR}/Run/eedomus.pass" ]; then
	EEDOMUS_PASS=$(cat ${CNF_DATADIR}/Run/eedomus.pass)
fi
EEDOMUS_IP=""
if [ -e "${CNF_DATADIR}/Run/eedomus.ip" ]; then
	EEDOMUS_IP=$(cat ${CNF_DATADIR}/Run/eedomus.ip)
fi
Log "[Home automation]" "Retrieve Eedomus data"
DATA='{"return":"0","user":"'${EEDOMUS_USER}'","pass":"'${EEDOMUS_PASS}'","ip":"'${EEDOMUS_IP}'"}'
SendResponse "${DATA}"
