#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/leds.inc

ReadUrlParams
FLASH_VERSION=${URLParam[version]:-$1}
CheckMandatoryParameter "${FLASH_VERSION}" version

KillProcess LED
KillProcess CROND
Leds ${ORANGE}

Log "[Update][Flash]" "Start Update to Firmware ${FLASH_VERSION}"

rm -f /tmp/rootfs.openkarotz.img.gz &>/dev/null
rm -f /tmp/rootfs.openkarotz.img.gz.md5 &>/dev/null

Leds ${ORANGE} ${BLACK} 1

Log "[Update][Flash]" "Downloading utility file(s)"
wget ${CNF_ROOT_URL}/Firmware/sounds/download.mp3 -q -O /tmp/download.mp3 &>/dev/null
PlaySound /tmp/download.mp3

wget ${CNF_ROOT_URL}/Firmware/sounds/install.mp3 -q -O /tmp/install.mp3 &>/dev/null
wget ${CNF_ROOT_URL}/Firmware/sounds/error.mp3 -q -O /tmp/error.mp3 &>/dev/null
wget ${CNF_ROOT_URL}/Firmware/sounds/ok.mp3 -q -O /tmp/ok.mp3 &>/dev/null

wget ${CNF_ROOT_URL}/Firmware/${FLASH_VERSION}/rootfs.openkarotz.img.gz -q -O /tmp/rootfs.openkarotz.img.gz &>/dev/null
wget ${CNF_ROOT_URL}/Firmware/${FLASH_VERSION}/rootfs.openkarotz.img.gz.md5 -q -O /tmp/rootfs.openkarotz.img.gz.md5 &>/dev/null

PlaySound /tmp/install.mp3
Leds ${ORANGE} ${BLACK} 1

if [ ! -e "/tmp/rootfs.openkarotz.img.gz" ]; then
	Log "[Update][Flash]" "rootfs file not found" 1
	PlaySound /tmp/error.mp3
	DATA='{"return":"1","msg":"rootfs file not found."}'
	SendResponse "${DATA}"
	exit 0
fi

if [ ! -e "/tmp/rootfs.openkarotz.img.gz.md5" ]; then
	Log "[Update][Flash]" "rootfs signature file not found" 1
	PlaySound /tmp/error.mp3
	DATA='{"return":"1","msg":"rootfs signature file not found."}'
	SendResponse "${DATA}"
	exit 0
fi

cd /tmp || exit
if md5sum -c -s /tmp/rootfs.openkarotz.img.gz.md5; then
	Log "[Update][Flash]" "rootfs integrity OK"
else
	Log "[Update][Flash]" "rootfs integrity verification failed" 1
	PlaySound /tmp/error.mp3
	DATA='{"return":"1","msg":"rootfs integrity verification failed."}'
	SendResponse "${DATA}"
	exit 0
fi

Log "[Update][Flash]" "Erasing flash"
/sbin/flash_eraseall -q /dev/mtd2

Log "[Update][Flash]" "Updating flash"
/sbin/nandwrite -q -pm /dev/mtd2 /tmp/rootfs.openkarotz.img.gz

rm -f /tmp/rootfs.openkarotz.img.gz &>/dev/null
rm -f /tmp/rootfs.openkarotz.img.gz.md5 &>/dev/null

Log "[Update][Flash]" "Flash succesfully updated to version ${FLASH_VERSION}"
PlaySound /tmp/ok.mp3

Leds ${CNF_BREEZE_COLOR} ${BLACK} 1

DATA='{"return":"0"}'
SendResponse "${DATA}"
reboot -d 15 &>/dev/null &
