#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

printf -v UTEMP '%s/patch.json' ${CNF_BASE_URL}
Log "[Update][Patch]" "Downloading patch list ${UTEMP}"
rm /tmp/patch.json &>/dev/null
curl --connect-timeout 30 -s -L -k -o /tmp/patch.json ${UTEMP}
if [ ! -e "/tmp/patch.json" ]; then
	Log "[Update][Patch]" "Unable read patch list" 1
	DATA='"{return":"1","msg":"Unable to read patch list"}'
else
	Log "[Update][Patch]" "Retrieve patch list"
	DATA=$(cat /tmp/patch.json)
fi
SendResponse "${DATA}"
