#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

printf -v UTEMP '%s/Firmware' ${CNF_ROOT_URL}
Log "[Update][Firmware]" "Downloading firmware list ${UTEMP}"
rm /tmp/firmware.json &>/dev/null
curl --connect-timeout 30 -s -L -k -o /tmp/firmware.json ${UTEMP}
if [ ! -e "/tmp/firmware.json" ]; then
	Log "[Update][Firmware]" "Unable read firmware list" 1
	DATA='{"return":"1","msg":"Unable to read firmware list"}'
else
	Log "[Update][Firmware]" "Retrieve firmware list"
	DATA=$(cat /tmp/firmware.json)
fi
SendResponse "${DATA}"
