#!/bin/bash

#TODO Rewrite not done yet!!!
source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

ReadUrlParams
LG=${URLParam[lang]:-"fr"}
CheckMandatoryParameter "${LG}" lang

#TODO is this file obsolete? Should we not use apps.moods version instead?
#TODO Why not use SendResponse? Rewrite not done yet
echo "Server: OpenKarotz WebServer 1.0 - Massalia 2013"
echo "Connection: close"
echo "Accept-Ranges: bytes"
#echo "Content-Length: "${#DATA}
echo "Content-type: text/plain"
echo ""

MDIR=${CNF_DATADIR}/Moods/${LG}
echo "Updating language: ${LG}"
if [ ! -d "${MDIR}" ]; then
   mkdir -p "${MDIR}"
fi
for ((i = 1; i < 400; i += 1)); do
   if [ ! -f "${CNF_DATADIR}/Moods/${LG}/${i}.mp3" ]; then
      curl -o "${CNF_DATADIR}/Moods/${LG}/${i}.mp3" http://s3.amazonaws.com/karotz/moods/${LG}/${i}.mp3 &>/dev/null
      echo "${i}.mp3: (D)"
   else
      echo "${i}.mp3"
   fi
done
echo "Done." #TODO sure about this?s
