#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

UFSP=-1
if mount | grep usbkey; then
   UFSP=$(df /mnt/usbkey 2>/dev/null | awk '{ print $5 }' | tail -n 1)
   UFSP="${UFSP%?}"
fi
KFSP=$(df /usr 2>/dev/null | awk '{ print $5 }' | tail -n 1)
KFSP="${KFSP%?}"
Log "[System]" "Karotz internal percentage used space: ${KFSP}"
Log "[System]" "Karotz USB percentage used space: ${UFSP}"
DATA='{"karotz_percent_used_space":"'${KFSP}'","usb_percent_used_space":"'${UFSP}'"}'
SendResponse "${DATA}"
