#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

PVERSION="N/A"
if [ -e "/www/ok_patch" ]; then
	PVERSION=$(cat /www/ok_patch)
fi
RVERSION="Unknown"
if [ -e "/karotz/etc/rootfs_version" ]; then
	RVERSION=$(cat /karotz/etc/rootfs_version)
fi
Log "[API]" "Retrieve version, patch_version and rootfs_version"
VL='{"return":"0","version":"'${CNF_VERSION}'","patch_version":"'${PVERSION}'","rootfs_version":"'${RVERSION}'"}'
SendResponse "${VL}"
