#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

ReadUrlParam

SRC=${URLParam[src]}
DEST=${URLParam[dest]}

wget $CNF_ROOT_URL/$SRC -O $CNF_DATADIR/$DEST

VL='{ "return":"0" }'

SendResponse "$VL"

