#!/bin/bash

#TODO looks like only fr exists... Double check!
echo "Downloading Moods"
echo "FR ----------------------------"
/www/cgi-bin/get_moods fr
echo "UK ----------------------------"
/www/cgi-bin/get_moods uk
echo "US ----------------------------"
/www/cgi-bin/get_moods us
echo "IT ----------------------------"
/www/cgi-bin/get_moods it
echo "ES ----------------------------"
/www/cgi-bin/get_moods es
echo "BE ----------------------------"
/www/cgi-bin/get_moods be
echo "BR ----------------------------"
/www/cgi-bin/get_moods br
