#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

HC2_IP=""
if [ -e "${CNF_DATADIR}/Run/hc2.ip" ]; then
	HC2_IP=$(cat ${CNF_DATADIR}/Run/hc2.ip)
fi
Log "[Home Automation]" "Retrieve Fibaro HC2 data"
DATA='{"return":"0","ip":"'${HC2_IP}'"}'
SendResponse "${DATA}"
