#!/bin/bash

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc

ReadUrlParam

echo "Server: OpenKarotz WebServer 1.0 - Massalia 2013"
echo "Connection: close"
echo "Accept-Ranges: bytes"
echo "Content-type: text/plain"
echo ""

# Checking Forced Update
FU=${URLParam[force]}
UU=${URLParam[usb]}


# Checking root Web
if [ ! -d $CNF_DATADIR/Apps ]; then
   mkdir $CNF_DATADIR/Apps >>/dev/null 2>>/dev/null
fi

if [ ! -d $CNF_DATADIR/Apps/Moods ]; then
   mkdir $CNF_DATADIR/Apps/Moods >>/dev/null 2>>/dev/null
fi

if [ ! -d $CNF_DATADIR/Apps/Moods/fr ]; then
   mkdir $CNF_DATADIR/Apps/Moods/fr >>/dev/null 2>>/dev/null
fi

Download $CNF_ROOT_URL /usbkey/Moods/fr $CNF_DATADIR/Apps/Moods/fr Moods 5

