#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

#TODO is this file obsolete? Should we not use apps.story.install instead?
#TODO Why not use SendResponse? Rewrite not done yet
echo "Server: OpenKarotz WebServer 1.0 - Massalia 2013"
echo "Connection: close"
echo "Accept-Ranges: bytes"
echo "Content-type: text/plain"
echo ""

# Checking root Web
if [ ! -d ${CNF_DATADIR}/Stories ]; then
	mkdir ${CNF_DATADIR}/Stories &>/dev/null
fi

Log "[Install][Apps]" "Story"
Download ${CNF_ROOT_URL} /usbkey/Stories ${CNF_DATADIR}/Stories Story 5
