#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

#TODO is this file obsolete? Should we not use apps.moods.install instead?
#TODO Only fr moods are installed -> how to integrate moods for other lang?
#TODO Why not use SendResponse? Rewrite not done yet
echo "Server: OpenKarotz WebServer 1.0 - Massalia 2013"
echo "Connection: close"
echo "Accept-Ranges: bytes"
echo "Content-type: text/plain"
echo ""

# Checking root Web
if [ ! -d ${CNF_DATADIR}/Apps/Moods/fr ]; then
	mkdir -p ${CNF_DATADIR}/Apps/Moods/fr &>/dev/null
fi
Log "[Install][Apps]" "Moods"
Download ${CNF_ROOT_URL} /usbkey/Moods/fr ${CNF_DATADIR}/Apps/Moods/fr Moods 5
