#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/leds.inc

CheckIsNotSleeping

CheckMandatoryDirectory "${CNF_DATADIR}/Run"
ReadUrlParams
LED_COLOR=${URLParam[color]}
LED_NOMEMORY=${URLParam[nomemory]:-0}
LED_PULSE=${URLParam[pulse]}
LED_BLINK=${URLParam[blink]}
LED_PULSE2=${URLParam[color2]:-${BLACK}}
LED_SPEED=${URLParam[speed]:-700}

if [ -n "${LED_PULSE}" ] && [ -n "${LED_BLINK}" ]; then
	Log "[LED]" "You cannot use BLINK and PULSE parameters at the same time" 1
	DATA='{"return":"1","msg":"You cannot use BLINK and PULSE parameters at the same time."}'
	SendResponse "${DATA}"
	exit 0
fi
if [ -z "${LED_COLOR}" ]; then
	LED_COLOR=${CNF_BREEZE_COLOR}
	if [ -e "${CNF_DATADIR}/Run/led.color" ]; then
		LED_COLOR=$(cat ${CNF_DATADIR}/Run/led.color)
	fi
fi
if [ -z "${LED_PULSE}" ]; then
	if [ ! -e "${CNF_DATADIR}/Run/led.pulse" ]; then
		LED_PULSE=0
	fi
fi
Log "[LED]" "Change LED cinematic"
KillProcess LED
Leds ${LED_COLOR} ${LED_PULSE2} ${LED_PULSE} ${LED_NOMEMORY} ${LED_SPEED}
DATA='{"return":"0","color":"'${LED_COLOR}'","secondary_color":"'${LED_PULSE2}'","pulse":"'${LED_PULSE}'","no_memory":"'${LED_NOMEMORY}'","speed":"'${LED_SPEED}'"}'
SendResponse "${DATA}"
