#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

ReadUrlParams
LG=${URLParam[lang]:-"fr"}
CheckMandatoryParameter "${LG}" lang

CheckMandatoryDirectory "${CNF_DATADIR}/Moods"
CheckMandatoryDirectory "${CNF_DATADIR}/Moods/${LG}"

if [ -e "${CNF_DATADIR}/Moods/${LG}/moods.lst" ]; then
	TG=''
	while IFS=':' read -r id text; do
		if [ -n "${text}" ]; then
			TG=${TG}'{ "id":"'${id}'","text":"'${text}'"},'
		fi
	done <"${CNF_DATADIR}/Moods/${LG}/moods.lst"
	Log "[Moods]" "Retrieve mood list"
	TG='{"return":"0","moods":['${TG%?}']}'
else
	Log "[Moods]" "Mood list not found" 1
	TG='{"return":"1","msg":"Mood list not found."}'
fi
SendResponse "${TG}"
