#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

Log "[Moods]" "Obsolete Moods function called"
DATA='{"return":"1","msg":"Obsolete! Moods app is now an Application. Use /cgi-bin/apps/moods instead."}'
SendResponse "${DATA}"
