#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

CheckMandatoryDirectory "${CNF_DATADIR}/Moods"
CheckMandatoryDirectory "${CNF_DATADIR}/Moods/fr"

if [ -e "${CNF_DATADIR}/Moods/fr/moods.json" ]; then
	Log "[Moods]" "Retrieve mood list"
	TG=$(cat ${CNF_DATADIR}/Moods/fr/moods.json)
else
	Log "[Moods]" "Mood list not found" 1
	TG='{"return":"1","msg":"Mood list not found."}'
fi
SendResponse "${TG}"
