#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

CheckMandatoryDirectory "${CNF_DATADIR}/Apps"
CheckMandatoryDirectory "${CNF_DATADIR}/Apps/Streams"

if [ -e "${CNF_DATADIR}/Apps/Streams/radios.json" ]; then
	Log "[Streams]" "Retrieve radio list"
	TG=$(cat ${CNF_DATADIR}/Apps/Streams/radios.json)
else
	Log "[Streams]" "Radio list not found" 1
	TG='{"return":"1","msg":"Radio list not found."}'
fi
SendResponse "${TG}"
