#!/bin/bash

source /www/cgi-bin/utils.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/setup.inc

ReadUrlParams
ID=${URLParam[id]}
FILE=${URLParam[file]}
CheckMandatoryParameter "${ID}" id
CheckMandatoryParameter "${FILE}" file

# Get update file from server
wget ${CNF_BASE_URL}/patch/${ID}/${FILE} -O /tmp/${FILE} -q &>/dev/null

# Check file
if [ ! -e "/tmp/${FILE}" ]; then
	Log "[Patch]" "Unable to get file: ${CNF_BASE_URL}/patch/${ID}/${FILE}" 1
	DATA='{"return":"1","msg":"Unable to read file."}'
else
	Log "[Patch]" "Reading file: ${CNF_BASE_URL}/Patch/${ID}/${FILE}"
	chmod 755 /tmp/${FILE} &>/dev/null

	# Launch update file
	Log "[Patch]" "Starting install patch"
	bash /tmp/${FILE} &>/dev/null

	# Remove update file
	rm -f /tmp/${FILE} &>/dev/null

	Log "[Patch]" "Patch installed"
fi
DATA='{"return":"0"}'
SendResponse "${DATA}"
