#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc
#source /www/cgi-bin/leds.inc

KillProcess
#Leds ${RED}

/sbin/reboot -d 10 &
Log "[System]" "Reboot"
DATA='{"return":"0"}'
SendResponse "${DATA}"
