#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

CheckMandatoryDirectory "${CNF_DATADIR}/Rfid"

KillProcess

# Check USB Key Availability
if ! mountpoint -q /mnt/usbkey; then
    DATA='{"return":"1","msg":"No USB key available for backup."}'
    SendResponse "${DATA}"
    exit
fi
NB=$(find ${CNF_DATADIR}/Rfid/ -type f -name "*.rfid" 2>/dev/null | wc -l)
if [ ${NB} -gt 0 ]; then
    BNAME="rfid.backup"
    cd ${CNF_DATADIR}/Rfid || exit
    tar cvf ${CNF_DATADIR}/${BNAME}.tar . &>/dev/null
    gzip /${CNF_DATADIR}/${BNAME}.tar &>/dev/null
    DATA='{"return":"0","file":"'${CNF_DATADIR}/${BNAME}.tar.gz'"}'
else
    DATA='{"return":"1","msg":"No Rfid informations to backup."}'
fi
SendResponse "${DATA}"
