#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url_ext.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/rfid.inc

cgi_getvars BOTH ALL
TAG_ID=${tag}
URL=$(echo ${url} | busybox base64 -d)
CheckMandatoryParameter "${TAG_ID}" tag
CheckMandatoryParameter "${URL}" url
URL=${curl-L -k -s -o /tmp/curlout "${URL}"}

CheckMandatoryTagId "${CNF_DATADIR}/Rfid" ${TAG_ID}

# Clear existing information
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.cmd &>/dev/null
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.var &>/dev/null
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.action &>/dev/null
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.name &>/dev/null

if [ -n "${TAG_ID}" ]; then
  echo ${RFID_ACTION_TYPE_KAROTZ} >${CNF_DATADIR}/Rfid/${TAG_ID}.cmd
  echo "-1" >${CNF_DATADIR}/Rfid/${TAG_ID}.var
  echo ${URL} | busybox base64 >${CNF_DATADIR}/Rfid/${TAG_ID}.action
fi
DATA='{"return":"0"}'
SendResponse "${DATA}"
