#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/rfid.inc

ReadUrlParams
TAG_ID=${URLParam[tag]}
NAME=${URLParam[name]}
COLOR=${URLParam[color]:-31}
CheckMandatoryParameter "${TAG_ID}" tag

CheckMandatoryTagId "${CNF_DATADIR}/Rfid" ${TAG_ID}

KillProcess

# Update informations
echo ${RFID_COLOR} >${CNF_DATADIR}/Rfid/${RFID_ID}.color
if [ -n "${NAME}" ]; then
     echo "${NAME}" | UrlDecode >${CNF_DATADIR}/Rfid/${TAG_ID}.name
else
     rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.name &>/dev/null
fi
echo "${COLOR}" >${CNF_DATADIR}/Rfid/${TAG_ID}.color
DATA='{"return":"0"}'
SendResponse "${DATA}"
