#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/leds.inc
source /www/cgi-bin/ears.inc

CheckMandatoryDirectory "${CNF_DATADIR}/Run"

KillProcess

PlaySound ${CNF_DATADIR}/Voice/Rfid_Start_Record.mp3 1
EarsReset
Leds ${YELLOW} ${RED} 1 1
echo "1" >${CNF_DATADIR}/Run/rfid.record
Log "[Rfid]" "Start recording Tag"
DATA='{"return":"0"}'
SendResponse "${DATA}"
