#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

CheckMandatoryDirectory "${CNF_DATADIR}/Rfid"

# Check Backup File Availability
if [ ! -e "${CNF_DATADIR}/rfid.backup.tar.gz" ]; then
  DATA='{"return":"1","msg":"No backup to restore."}'
  SendResponse "${DATA}"
  exit
fi

KillProcess

cd ${CNF_DATADIR}/Rfid || exit
mv ${CNF_DATADIR}/rfid.backup.tar.gz ${CNF_DATADIR}/Rfid
tar zxvf ${CNF_DATADIR}/Rfid/rfid.backup.tar.gz
rm -f ${CNF_DATADIR}/Rfid/rfid.backup.tar.gz
Log "[Rfid]" "Tags restored."
DATA='{"return":"0"}'
SendResponse "${DATA}"
