#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/rfid.inc

CheckMandatoryDirectory "${CNF_DATADIR}/Rfid"

TG=''
while read -r f; do
    TAG_ID=$(echo ${f} | cut -d '/' -f 5 | cut -d '.' -f 1)
    TAG_TYPE=$(ReadParam ${CNF_DATADIR}/Rfid/${TAG_ID}.type -1)
    TAG_COLOR=$(ReadParam ${CNF_DATADIR}/Rfid/${TAG_ID}.color -1)
    TAG_CMD=$(ReadParam ${CNF_DATADIR}/Rfid/${TAG_ID}.cmd 0)
    TAG_VAR=$(ReadParam ${CNF_DATADIR}/Rfid/${TAG_ID}.var -1)
    TAG_NAME=$(ReadParam ${CNF_DATADIR}/Rfid/${TAG_ID}.name "")
    TG=${TG}'{ "id":"'${TAG_ID}'","type":"'${TAG_TYPE}'","color":"'${TAG_COLOR}'","cmd":"'${TAG_CMD}'","var":"'${TAG_VAR}'","name":"'${TAG_NAME}'"},'
done < <(find ${CNF_DATADIR}/Rfid/ -type f -name "*.rfid")
DATA='{"return":"0","tags":['${TG%?}']}'
SendResponse "${DATA}"
