#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/rfid.inc

ReadUrlParams
TAG_ID=${URLParam[tag]}
CheckMandatoryParameter "${TAG_ID}" tag

CheckMandatoryTagId "${CNF_DATADIR}/Rfid" ${TAG_ID}

KillProcess

# Clear existing information
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.cmd &>/dev/null
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.var &>/dev/null
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.action &>/dev/null
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.name &>/dev/null
Log "[Rfid]" "Tag unassigned."
DATA='{"return":"0","tag":"'${TAG_ID}'"}'
SendResponse "${DATA}"
