#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/rfid.inc

ReadUrlParams
TAG_ID=${URLParam[tag]}
VERA_IP=${URLParam[ip]}
SCENE_ID=${URLParam[scene]}
NAME=${URLParam[name]}
CheckMandatoryParameter "${TAG_ID}" tag
CheckMandatoryParameter "${VERA_IP}" ip
CheckMandatoryParameter "${SCENE_ID}" scene

CheckMandatoryTagId "${CNF_DATADIR}/Rfid" ${TAG_ID}

# Clear existing information
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.cmd &>/dev/null
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.var &>/dev/null
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.action &>/dev/null
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.name &>/dev/null

echo ${RFID_ACTION_TYPE_VERA} >${CNF_DATADIR}/Rfid/${TAG_ID}.cmd
echo ${SCENE_ID} >${CNF_DATADIR}/Rfid/${TAG_ID}.var
if [ -n "${NAME}" ]; then
  echo "${NAME}" | UrlDecode >${CNF_DATADIR}/Rfid/${TAG_ID}.name
fi
URL=$(BuildVeraUrl ${VERA_IP} ${SCENE_ID})
echo ${URL} | busybox base64 >${CNF_DATADIR}/Rfid/${TAG_ID}.action
DATA='{"return":"0"}'
SendResponse "${DATA}"
