#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/rfid.inc

ReadUrlParams
TAG_ID=${URLParam[tag]}
EEDOMUS_IP=${URLParam[ip]}
EEDOMUS_USER=${URLParam[api_user]}
EEDOMUS_PASS=${URLParam[api_password]}
MACRO_ID=${URLParam[macro]}
NAME=${URLParam[name]}
PORTAL=${URLParam[portal]}
CheckMandatoryParameter "${TAG_ID}" tag
CheckMandatoryParameter "${EEDOMUS_IP}" ip
CheckMandatoryParameter "${EEDOMUS_USER}" api_user
CheckMandatoryParameter "${EEDOMUS_PASS}" api_password
CheckMandatoryParameter "${MACRO_ID}" macro
CheckMandatoryParameter "${PORTAL}" portal

CheckMandatoryTagId "${CNF_DATADIR}/Rfid" ${TAG_ID}

# Clear existing information
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.cmd &>/dev/null
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.var &>/dev/null
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.action &>/dev/null
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.name &>/dev/null

echo ${RFID_ACTION_TYPE_EEDOMUS} >${CNF_DATADIR}/Rfid/${TAG_ID}.cmd
echo ${MACRO_ID} >${CNF_DATADIR}/Rfid/${TAG_ID}.var
if [ -n "${NAME}" ]; then
	echo "${NAME}" | UrlDecode >${CNF_DATADIR}/Rfid/${TAG_ID}.name
fi
URL=$(BuildEeDomusUrl ${EEDOMUS_IP} ${MACRO_ID} ${EEDOMUS_USER} ${EEDOMUS_PASS} 0 ${PORTAL})
echo ${URL} | busybox base64 >${CNF_DATADIR}/Rfid/${TAG_ID}.action
Log "[Rfid]" "Eedomus macro assigned to tag"
DATA='{"return":"0"}'
SendResponse "${DATA}"
