#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/url_ext.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/rfid.inc

cgi_getvars BOTH ALL
TAG_ID=${tag}
URL=${url}
RAW_PARAM=${param}
NAME=${name}
USR=${user}
PASS=${password}
CheckMandatoryParameter "${TAG_ID}" tag
CheckMandatoryParameter "${URL}" url

CheckMandatoryTagId "${CNF_DATADIR}/Rfid" ${TAG_ID}

# Clear existing information
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.cmd &>/dev/null
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.var &>/dev/null
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.action &>/dev/null
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.name &>/dev/null

echo ${RFID_ACTION_TYPE_URL} >${CNF_DATADIR}/Rfid/${TAG_ID}.cmd
echo "-1" >${CNF_DATADIR}/Rfid/${TAG_ID}.var
if [ -n "${NAME}" ]; then
    echo "${NAME}" | UrlDecode >${CNF_DATADIR}/Rfid/${TAG_ID}.name
fi
PARAM=$(echo "${RAW_PARAM}" | busybox base64 -d)
URL=$(BuildUrl "${URL}" "${PARAM}" "${USR}" "${PASS}")
echo "${URL}" | busybox base64 >${CNF_DATADIR}/Rfid/${TAG_ID}.action
DATA='{"return":"0"}'
SendResponse "${DATA}"
