#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/leds.inc

CheckMandatoryDirecrory "${CNF_DATADIR}/Run"

KillProcess

rm -f ${CNF_DATADIR}/Run/rfid.record &>/dev/null
PlaySound ${CNF_DATADIR}/Voice/Rfid_Stop_record.mp3
LedsRestore
Log "[Rfid]" "Stop recording tag"
DATA='{"return":"0"}'
SendResponse "${DATA}"
