#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/rfid.inc

ReadUrlParams
TAG_ID=${URLParam[tag]}
ZIBASE_IP=${URLParam[ip]}
CMD_ID=${URLParam[cmd]}
CheckMandatoryParameter "${TAG_ID}" tag
CheckMandatoryParameter "${ZIBASE_IP}" ip
CheckMandatoryParameter "${CMD_ID}" cmd

CheckMandatoryTagId "${CNF_DATADIR}/Rfid" ${TAG_ID}

KillProcess

# Clear existing information
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.cmd &>/dev/null
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.var &>/dev/null
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.action &>/dev/null
rm -f ${CNF_DATADIR}/Rfid/${TAG_ID}.name &>/dev/null

echo ${RFID_ACTION_TYPE_ZIBASE} >${CNF_DATADIR}/Rfid/${TAG_ID}.cmd
echo ${CMD_ID} >${CNF_DATADIR}/Rfid/${TAG_ID}.var
if [ -n "${NAME}" ]; then
  echo "${NAME}" | UrlDecode >${CNF_DATADIR}/Rfid/${TAG_ID}.name
fi
URL=$(BuildZibaseUrl ${ZIBASE_IP} ${CMD_ID})
echo ${URL} | busybox base64 >${CNF_DATADIR}/Rfid/${TAG_ID}.action
DATA='{"return":"0"}'
SendResponse "${DATA}"
