#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

ntpd -n -q -p pool.ntp.org 2>>/var/log/messages
Log "[System]" "Clock set via ntpd"
DATA='{"return":"0"}'
SendResponse "${DATA}"
