#!/bin/bash
#
# Global parameters
#
# Max Files in cache
CNF_MAX_CACHE_SIZE=100 #TODO Unused

# File Location
CNF_DATADIR="/usr/openkarotz"

# Disable Ears
CNF_EARS_DISABLED=0 #TODO Unused

# RFID Action active even when Karotz is sleeping
CNF_RFID_ALWAYS_ACTIVE=1 #TODO Unused

# Breeze Color
CNF_BREEZE_COLOR=00FF00

# Karotz Gender
# M : Male
# F : Female
CNF_GENDER=F #TODO Unused

# Version
CNF_VERSION="210"

# Root URL
CNF_ROOT_URL="http://karotz.filippi.org"

# Base URL
CNF_BASE_URL="${CNF_ROOT_URL}/${CNF_VERSION}"
