#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/leds.inc
source /www/cgi-bin/ears.inc

CheckIsNotSleeping

KillProcess

Log "[API]" "Going to sleep"
EarsReset
Leds ${CYAN} ${CNF_BREEZE_COLOR} 1
EarsMove 5 5 50
Leds ${BLACK}
echo "1" >${CNF_DATADIR}/Run/karotz.sleep
date +%s >${CNF_DATADIR}/Run/karotz.time.sleep
DATA='{"return":"0"}'
SendResponse "${DATA}"
