#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/leds.inc
source /www/cgi-bin/webcam.inc

ReadUrlParams
SILENT=${URLParam[silent]:-0}

FN="snapshot_$(date +'%Y_%m_%d_%H_%M_%S')"
CheckMandatoryDirectory "${CNF_DATADIR}/Snapshots"

KillProcess LED

TakeSnapshot
if [ ! -e "${CNF_DATADIR}/Run/karotz.sleep" ]; then
    LedsRestore
    if [ ${SILENT} -eq 0 ]; then
        PlaySound /usr/karotz/res/sounds/webcam.mp3
    fi
fi
if [ ! -e "/tmp/picture.jpg" ]; then
    Log "[Snapshot]" "Unable to take a snapshot" 1
    DATA='{"return":"1","msg":"Unable to take a snapshot."}'
else
    Log "[Snapshot]" "Snapshot saved"
    mv /tmp/picture.jpg "${CNF_DATADIR}/Snapshots/${FN}.jpg"
    #TODO a new way to create thumbnail could be great
    /usr/bin/arm-linux-djpeg -gif -scale 1/4 -outfile "${CNF_DATADIR}/Snapshots/${FN}.thumb.gif" "${CNF_DATADIR}/Snapshots/${FN}.jpg"
    DATA='{"return":"0","filename":"'${FN}'.jpg","thumb":"'${FN}'.thumb.gif"}'
fi
SendResponse "${DATA}"
