#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

ReadUrlParams
FNAME=${URLParam[filename]}
CheckMandatoryParameter "${FNAME}" filename

CheckMandatoryDirectory "${CNF_DATADIR}/Snapshots"

KillProcess

#TODO SendResponse for jpeg! Rewrite not done yet
echo "Server: OpenKarotz WebServer 1.0 - Massalia 2013"
echo "Connection: close"
echo "Accept-Ranges: bytes"
# echo "Content-Disposition: attachment; filename="${FNAME}
echo "Cache-Control: private"
echo "Pragma: private"
echo "Content-type: image/jpeg"
echo ""
if [ -e "${CNF_DATADIR}/Snapshots/${FNAME}" ]; then
	cat "${CNF_DATADIR}/Snapshots/${FNAME}"
fi
