#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

CheckMandatoryDirectory "${CNF_DATADIR}/Snapshots/"

Log "[Snapshot]" "Retrieve snapshot list"
TG=''
while read -r f; do
    TG=${TG}'{"id":"'$(echo ${f} | cut -d '/' -f 5)'"},'
done < <(find ${CNF_DATADIR}/Snapshots/ -type f -name "*.jpg")
DATA='{"return":"0","snapshots":['${TG%?}']}'
SendResponse "${DATA}"
