#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

CheckMandatoryDirectory "${CNF_DATADIR}/Sounds"

Log "[Sounds]" "Retrieve sound list"
TG=''
while read -r f; do
   FNAME=$(echo ${f} | cut -d '/' -f 5)
   TG=${TG}'{ "id":"'${FNAME%%.*}'"},'
done < <(find ${CNF_DATADIR}/Sounds/ -type f -name "*.mp3")
DATA='{"return":"0","sounds":['${TG%?}']}'
SendResponse "${DATA}"
