#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

CheckIsNotSleeping

ReadUrlParams
CMD=${URLParam[cmd]}
CheckMandatoryParameter "${CMD}" cmd

CHECK=$(busybox pgrep mplayer 2>/dev/null | wc -l)
if [ ${CHECK} -gt 1 ]; then
    DCMD=$(echo ${CMD} | UrlDecode)
    echo ${DCMD} >/tmp/mplayer-control
    Log "[Sounds]" "Command launched"
    DATA='{"return":"0","cmd":"'${DCMD}'"}'
else
    Log "[Sounds]" "No sound currently playing" 1
    DATA='{"return":"1","msg":"No sound currently playing."}'
fi
SendResponse "${DATA}"
