#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

CheckIsNotSleeping

ReadUrlParams
SOUND_ID=${URLParam[id]}
SOUND_URL=${URLParam[url]}

if [ -n "${SOUND_ID}" ] && [ -n "${SOUND_URL}" ]; then
	Log "[Sounds]" "Too many parameters set: ID and URL" 1
	DATA='{"return":"1","msg":"You cannot use ID and URL parameters at the same time."}'
elif [ -n "${SOUND_ID}" ]; then
	if [ -e "${CNF_DATADIR}/Sounds/${SOUND_ID}.mp3" ]; then
		KillProcess SOUNDS
		PlaySound ${CNF_DATADIR}/Sounds/${SOUND_ID}.mp3
		Log "[Sounds]" "Playing sound ${SOUND_ID}"
		DATA='{"return":"0","id":"'${SOUND_ID}'"}'
	else
		Log "[Sounds]" "Sound not found: ${SOUND_ID}" 1
		DATA='{"return":"1","msg":"Sound not found."}'
	fi
elif [ -n "${SOUND_URL}" ]; then
	Log "[Sounds]" "Playing sound ${SOUND_URL}"
	KillProcess SOUNDS
	sleep 1
	PlaySoundEx ${SOUND_URL} 1
	DATA='{"return":"'$?'","url": "'${SOUND_URL}'"}'
elif [ -z "${SOUND_ID}" ] && [ -z "${SOUND_URL}" ]; then
	Log "[Sounds]" "No sound to play" 1
	DATA='{"return":"1","msg":"No sound to play."}'
fi
SendResponse "${DATA}"
