#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/leds.inc

CheckIsNotSleeping

ReadUrlParams
CMD=${URLParam[cmd]}

CheckMandatoryParameter "${CMD}" cmd

if ifconfig -a | grep wlan0 &>/dev/null; then
	MAC=$(ifconfig wlan0 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}') &>/dev/null
else
	if ifconfig -a | grep eth0 &>/dev/null; then
		MAC=$(ifconfig eth0 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}') &>/dev/null
	else
		MAC="00:00:00:00:00:00"
	fi
fi

CHECK=$(busybox pgrep squeezeslave 2>/dev/null | wc -l)
if [ "${CMD}" == "start" ]; then
	if [ ${CHECK} -gt 1 ]; then
		Log "[Sounds]" "Squeezebox already running" 1
		DATA='{"return":"1","msg":"Squeezebox already running."}'
	else
		Log "[Sounds]" "Start Squeezebox Player"
		KillProcess SOUNDS
		Leds ${BLUE} ${BLACK} 1 1
		squeezeslave -F -M /tmp/squeezebox.log -m ${MAC}
		DATA='{"return":"0"}'
	fi
elif [ "${CMD}" == "stop" ]; then
	if [ ${CHECK} -gt 1 ]; then
		Log "[Sounds]" "Stop Squeezebox Player"
		KillProcess SOUNDS
		LedsRestore
		DATA='{"return":"0"}'
	else
		Log "[Sounds]" "Squeezebox not running" 1
		DATA='{"return":"1","msg":"Squeezebox not running."}'
	fi
else
	Log "[Sounds]" "Unknown command" 1
	DATA='{"return":"1","msg":"Unknown command."}'
fi
SendResponse "${DATA}"
