#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

/www/cgi-bin/start_ok &>/dev/null &

DATA='{"return":"0","msg":"OpenKarotz launched with success."}'
SendResponse "${DATA}"
exit 0
