#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

CheckMandatoryDirectory "${CNF_DATADIR}/Stories"

if [ -e "${CNF_DATADIR}/Stories/stories.json" ]; then
    TG=$(cat ${CNF_DATADIR}/Stories/stories.json)
else
    TG='{"return":"0","stories":[]}'
fi
SendResponse "${TG}"
