#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

CheckIsNotSleeping

ReadUrlParams
STORY_ID=${URLParam[id]}
CheckMandatoryParameter "${STORY_ID}" id

KillProcess

if [ -e "${CNF_DATADIR}/Stories/${STORY_ID}".mp3 ]; then
   PlaySound ${CNF_DATADIR}/Stories/${STORY_ID}.mp3
   DATA='{"return":"0"}'
else
   DATA='{"return":"1","msg":"Story not found: '${STORY_ID}'."}'
fi
SendResponse "${DATA}"
