#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

Log "[Rfid]" "Obsolete Rfid function called"
DATA='{"return":"1","msg":"Obsolete, use rfid_list instead."}'
SendResponse "${DATA}"
