#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

ReadUrlParams
CMD=${URLParam[cmd]}
CheckMandatoryParameter "${CMD}" cmd

case ${CMD} in
  "start")
    killall syslogd &>/dev/null
    touch /etc/conf/enable_syslogd
    /sbin/syslogd -s 50 -b 2
    Log "[Tools]" "Log system started"
    DATA='{"return":"0","msg":"Log system started."}'
    ;;
  "stop")
    rm -f /etc/conf/enable_syslogd &>/dev/null
    killall syslogd &>/dev/null
    Log "[Tools]" "Log system stopped"
    DATA='{"return":"0","msg":"Log system stopped."}'
    ;;
  *)
    Log "[Tools]" "Command not found" 1
    DATA='{"return":"1","msg":"Command not found."}'
    ;;
esac
SendResponse "${DATA}"
