#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

VL=""
if [ -e "/var/log/messages" ]; then
  tail -q -n 200 /var/log/messages > /tmp/messages.txt
  VL=`awk '{printf "%s\n\r", $0}' /tmp/messages.txt`
  rm -f /tmp/messages.txt
fi

SendResponse "$VL"

