#!/bin/bash

#TODO Duplicate tools_ps, TO DELETE!
source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

VL=$(ps eax | awk '{printf "%s\r\n", $0}')
Log "[Tools]" "Retrieve active process list"
SendResponse "${VL}"
