#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

VL=""
if [ -e "/var/log/messages" ]; then
    Log "[Tools]" "Retrieve last log messages"
    VL=$(tail -q -n 200 /var/log/messages | awk '{printf "%s\r\n, $0}')
fi
SendResponse "${VL}"
