#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/tts.inc

CheckIsNotSleeping

ReadUrlParams
# TTS ENGINE
#  Use ACAPELA Engine by default
#  0=ACAPELA
#  1=GOOGLE
#  2=VIOLET
TTS_ENGINE=${URLParam[engine]:-0}
TTS=${URLParam[text]}
RAW_VOICE=${URLParam[voice]:-margaux}
SPEED=${URLParam[speed]} #TODO unused?
NO_CACHE=${URLParam[nocache]:-0}
MUTE=${URLParam[mute]:-0}
CheckMandatoryParameter "${TTS}" text
#CheckMandatoryParameter "${RAW_VOICE}" voice

CheckMandatoryDirectory "${CNF_DATADIR}/Tmp"

KillProcess SOUNDS

PLAYED=0
CACHE=0
VOICE=${RAW_VOICE}"22k"
MD5FILE=$(echo "${TTS}${VOICE}" | md5sum | cut -d ' ' -f 1)
if [ -e "${CNF_DATADIR}/Tmp/${MD5FILE}.txt" ] && [ ${NO_CACHE} -eq 0 ]; then
	CACHE=1
	if [ ${MUTE} -ne 1 ]; then
		Log "[TTS]" "Playing sound ${MD5FILE}.mp3 from cache"
		PlaySound ${CNF_DATADIR}/Tmp/${MD5FILE}.mp3
	fi
else
	case ${TTS_ENGINE} in
		1) MP3_ID=$(GoogleTTS ${TTS} ${VOICE} ${NO_CACHE} ${RAW_VOICE}) ;;
		2) MP3_ID=$(VioletTTS ${TTS} ${VOICE} ${NO_CACHE} ${RAW_VOICE}) ;;
		*) MP3_ID=$(AcapelaTTS ${TTS} ${VOICE} ${NO_CACHE} ${RAW_VOICE} ${MUTE}) ;;
	esac
fi
PLAYED=1
DATA='{"return":"'$?'","id":"'${MP3_ID}'","played":"'${PLAYED}'","cache":"'${CACHE}'","voice":"'${RAW_VOICE}'","mute":"'${MUTE}'"}'
SendResponse "${DATA}"
