#!/bin/bash

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc

TDIR="/usr/www"

ReadUrlParam

echo "Server: OpenKarotz WebServer 1.0 - Massalia 2013"
echo "Connection: close"
echo "Accept-Ranges: bytes"
echo "Content-type: text/plain"
echo ""

# Checking Forced Update
FU=${URLParam[force]}
UU=${URLParam[usb]}

if [ "$FU" == "1" ] || [ "$1" == "1" ]; then
 rm -f $TDIR/ok.version >>/dev/null 2>>/dev/null
fi

# Checking root Web
if [ ! -d $TDIR ]; then
   mkdir $TDIR >>/dev/null 2>>/dev/null
fi

# Checking cgi-bin
if [ ! -d $TDIR/cgi-bin ]; then
   mkdir $TDIR/cgi-bin >>/dev/null 2>>/dev/null
fi

# Checking images
if [ ! -d $TDIR/images ]; then
   mkdir $TDIR/images >>/dev/null 2>>/dev/null
fi

# Checking Snapshots
if [ ! -d $TDIR/snapshots ]; then
   mkdir $TDIR/snapshots >>/dev/null 2>>/dev/null
fi

# Get local version
if [ ! -f $TDIR/ok.version ]; then
   LV=0
else
   LV=$(cat $TDIR/ok.version  )
fi

# Create pipes for Program Control
#if [ ! -f /tmp/mpd_control ]; then
#   mknod /tmp/mpd_control p  >>/dev/null 2>>/dev/null
#fi

if [ ! -f /tmp/mplayer-control ]; then
   mknod /tmp/mplayer-control p  >>/dev/null 2>>/dev/null
fi


# Get server Version
rm $TDIR/server.ok.version >>/dev/null 2>>/dev/null
echo "----------------------------------------"
wget $CNF_ROOT_URL/ok.version -q -O $TDIR/server.ok.version
RV=$(cat $TDIR/server.ok.version )

# Display version
echo -n "Server Version : "
echo $RV
echo -n "Local Version  : "
echo $LV


if [ "${LV:-0}" -ge "${RV:-0}" ] ; then
	echo "----------------------------------------"
  	echo "No update needed"
else
    # Update local version
    rm -f $TDIR/ok.version >>/dev/null 2>>/dev/null
    mv $TDIR/server.ok.version $TDIR/ok.version >>/dev/null 2>>/dev/null
    echo "Web Root  : "$TDIR
    echo "Data Root : "$CNF_DATADIR

    # Get Web Server Config File
    echo "----------------------------------------"
    echo "Updating Web Server Config"
    echo "----------------------------------------"
    wget $CNF_ROOT_URL/httpd.conf -O /usr/httpd.conf -q > /dev/null

	echo "----------------------------------------"
	echo "Updating startup Script"
	echo "----------------------------------------"
	if [ ! -e "/usr/yaffs_start.sh.backup.ok" ]; then
		 cp /usr/yaffs_start.sh /usr/yaffs_start.sh.backup.ok
		 echo "# ----------------------------------------" >> /usr/yaffs_start.sh
		 echo "# Open Karotz modification" >> /usr/yaffs_start.sh
		 echo "# ----------------------------------------" >> /usr/yaffs_start.sh
		 echo "ntpd -n -q -p pool.ntp.org" >> /usr/yaffs_start.sh
		 echo "mount /dev/uba1 /mnt/usbkey" >> /usr/yaffs_start.sh
		 echo "/usr/www/cgi-bin/start_ok" >> /usr/yaffs_start.sh
		 echo "# ----------------------------------------" >> /usr/yaffs_start.sh
		 echo "" >> /usr/yaffs_start.sh
     fi

    # Updating /www
    #URL=$1
    #RDIR=$2
    #LDIR=$3
    #NAME=$4
    #GROUP=$5
    Download $CNF_ROOT_URL /www /usr/www "Pages Web" 1

    # Updating /www/cgi-bin
    Download $CNF_ROOT_URL /www/cgi-bin /usr/www/cgi-bin "Scripts" 5

    # Updating Images
    Download $CNF_ROOT_URL /www/images /usr/www/images "Images" 1

    echo "----------------------------------------"
    echo Checking Data Structure
    echo "----------------------------------------"

	# Updating Data Path
	#
	if [ "$UU" == "1" ] || [ "$2" == "1" ]; then

        if [ ! -d "$CNF_DATADIR/Stories" ]; then
            mkdir $CNF_DATADIR/Stories >>/dev/null 2>>/dev/null
            echo -n "."
        else
            echo -n "o"
        fi

        if [ ! -d "$CNF_DATADIR/Moods" ]; then
           	mkdir $CNF_DATADIR/Moods >>/dev/null 2>>/dev/null
			echo -n "."
        else
           echo -n "o"
        fi

        if [ ! -d "$CNF_DATADIR/Moods/fr" ]; then
           	mkdir $CNF_DATADIR/Moods/fr >>/dev/null 2>>/dev/null
			echo -n "."
        else
           echo -n "o"
        fi

        if [ ! -d "$CNF_DATADIR/Run" ]; then
           mkdir $CNF_DATADIR/Run >>/dev/null 2>>/dev/null
           echo -n "."
        else
           echo -n "o"
        fi

        if [ ! -d "$CNF_DATADIR/Rfid" ]; then
        	mkdir $CNF_DATADIR/Rfid >>/dev/null 2>>/dev/null
            echo -n "."
        else
           	echo -n "o"
        fi

        if [ ! -d "$CNF_DATADIR/Sounds" ]; then
           mkdir $CNF_DATADIR/Sounds >>/dev/null 2>>/dev/null
           echo -n "."
        else
           echo -n "o"
        fi

         if [ ! -d "$CNF_DATADIR/Tmp" ]; then
           mkdir $CNF_DATADIR/Tmp >>/dev/null 2>>/dev/null
           echo -n "."
        else
           echo -n "o"
        fi

        if [ ! -d "$CNF_DATADIR/Voice" ]; then
           mkdir $CNF_DATADIR/Voice >>/dev/null 2>>/dev/null
           echo -n "."
        else
           echo -n "o"
        fi

        if [ ! -d "$CNF_DATADIR/Rfid" ]; then
           	mkdir $CNF_DATADIR/Rfid >>/dev/null 2>>/dev/null
			echo -n "."
        else
           	echo -n "o"
        fi
        echo ""

  		# Updating Voices
        Download $CNF_ROOT_URL /usbkey/Voice $CNF_DATADIR/Voice "Voices" 1

        # Updating Sounds
        Download $CNF_ROOT_URL /usbkey/Sounds $CNF_DATADIR/Sounds "Sounds" 1

    fi
fi
echo "----------------------------------------"
echo  Done
echo  You must now manually update Moods and Stories
echo  from Update Tab
echo "----------------------------------------"
echo "Power Cycle your Rabbit to finish Installation."
/usr/bin/madplay $CNF_DATADIR/Voice/install_ok.mp3 >>/dev/null 2>>/dev/null
echo "----------------------------------------"




