#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

#TODO Is duplicated by update

ReadUrlParams
# Checking Forced Update
FU=${URLParam[force]:-${1:-0}}
UU=${URLParam[usb]:-${2:-0}}

if [ ${FU} -eq 1 ]; then
	rm -f ${TDIR}/ok.version &>/dev/null
fi

#TODO See if we can not replace each mkdir by CheckMandatoryDirectory function??
# Checking root Web
if [ ! -d ${TDIR} ]; then
	mkdir ${TDIR} &>/dev/null
fi
# Checking cgi-bin
if [ ! -d ${TDIR}/cgi-bin ]; then
	mkdir ${TDIR}/cgi-bin &>/dev/null
fi
# Checking images
if [ ! -d ${TDIR}/images ]; then
	mkdir ${TDIR}/images &>/dev/null
fi
# Checking Snapshots
if [ ! -d ${TDIR}/snapshots ]; then
	mkdir ${TDIR}/snapshots &>/dev/null
fi

# Create pipes for Program Control
#TODO to clean? mplayer-control instead of mpd_control?
#if [ ! -f /tmp/mpd_control ]; then
#	mknod /tmp/mpd_control p  &>/dev/null
#fi
if [ ! -f /tmp/mplayer-control ]; then
	mknod /tmp/mplayer-control p &>/dev/null
fi

# Get local version
LV=0
if [ -f ${TDIR}/ok.version ]; then
	LV=$(cat ${TDIR}/ok.version)
fi
# Get server Version
rm ${TDIR}/server.ok.version &>/dev/null
wget ${CNF_ROOT_URL}/ok.version -q -O ${TDIR}/server.ok.version
RV=$(cat ${TDIR}/server.ok.version)

# Display version
#TODO Why not use SendResponse? Rewrite not done yet
echo "Server: OpenKarotz WebServer 1.0 - Massalia 2013"
echo "Connection: close"
echo "Accept-Ranges: bytes"
echo "Content-type: text/plain"
echo ""
echo "----------------------------------------"
echo "Server Version: "${RV}
echo "Local Version: "${LV}

if [ ${LV:-0} -ge ${RV:-0} ]; then
	echo "----------------------------------------"
	echo "No update needed"
else
	# Update local version
	rm -f ${TDIR}/ok.version &>/dev/null
	mv ${TDIR}/server.ok.version ${TDIR}/ok.version &>/dev/null
	echo "Web Root: "${TDIR}
	echo "Data Root: "${CNF_DATADIR}
	# Get Web Server Config File
	echo "----------------------------------------"
	echo "Updating Web Server Config"
	echo "----------------------------------------"
	wget ${CNF_ROOT_URL}/httpd.conf -O /usr/httpd.conf -q
	echo "----------------------------------------"
	echo "Updating startup Script"
	echo "----------------------------------------"
	if [ ! -e "/usr/yaffs_start.sh.backup.ok" ]; then
		cp /usr/yaffs_start.sh /usr/yaffs_start.sh.backup.ok
		{
			echo "# ----------------------------------------"
			echo "# OpenKarotz modification"
			echo "# ----------------------------------------"
			echo "ntpd -n -q -p pool.ntp.org"
			echo "mount /dev/uba1 /mnt/usbkey"
			echo "/www/cgi-bin/start_ok"
			echo "# ----------------------------------------"
			echo ""
		} >>/usr/yaffs_start.sh
	fi

	# Updating /www
	Download ${CNF_ROOT_URL} /www /www "Pages Web" 1
	# Updating /www/cgi-bin
	Download ${CNF_ROOT_URL} /www/cgi-bin /www/cgi-bin "Scripts" 5
	# Updating Images
	Download ${CNF_ROOT_URL} /www/images /www/images "Images" 1

	echo "----------------------------------------"
	echo Checking Data Structure
	echo "----------------------------------------"
	# Updating Data Path
	if [ ${UU} -eq 1 ]; then
		if [ ! -d "${CNF_DATADIR}/Stories" ]; then
			mkdir ${CNF_DATADIR}/Stories &>/dev/null
			echo -n "."
		else
			echo -n "o"
		fi
		if [ ! -d "${CNF_DATADIR}/Moods/fr" ]; then
			mkdir -p ${CNF_DATADIR}/Moods/fr &>/dev/null
			echo -n "."
		else
			echo -n "o"
		fi
		if [ ! -d "${CNF_DATADIR}/Run" ]; then
			mkdir ${CNF_DATADIR}/Run &>/dev/null
			echo -n "."
		else
			echo -n "o"
		fi
		if [ ! -d "${CNF_DATADIR}/Rfid" ]; then
			mkdir ${CNF_DATADIR}/Rfid &>/dev/null
			echo -n "."
		else
			echo -n "o"
		fi
		if [ ! -d "${CNF_DATADIR}/Sounds" ]; then
			mkdir ${CNF_DATADIR}/Sounds &>/dev/null
			echo -n "."
		else
			echo -n "o"
		fi
		if [ ! -d "${CNF_DATADIR}/Tmp" ]; then
			mkdir ${CNF_DATADIR}/Tmp &>/dev/null
			echo -n "."
		else
			echo -n "o"
		fi
		if [ ! -d "${CNF_DATADIR}/Voice" ]; then
			mkdir ${CNF_DATADIR}/Voice &>/dev/null
			echo -n "."
		else
			echo -n "o"
		fi
		echo ""

		# Updating Voices
		Download ${CNF_ROOT_URL} /usbkey/Voice ${CNF_DATADIR}/Voice "Voices" 1
		# Updating Sounds
		Download ${CNF_ROOT_URL} /usbkey/Sounds ${CNF_DATADIR}/Sounds "Sounds" 1
	fi
fi
echo "----------------------------------------"
echo Done
echo You must now manually update Moods and Stories
echo from Update Tab
echo "----------------------------------------"
echo "Power Cycle your Rabbit to finish Installation."
echo "----------------------------------------"
/usr/bin/madplay ${CNF_DATADIR}/Voice/install_ok.mp3 &>/dev/null
