#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

VERA_IP=""
if [ -e "${CNF_DATADIR}/Run/vera.ip" ]; then
	VERA_IP=$(cat ${CNF_DATADIR}/Run/vera.ip)
fi
Log "[Home Automation]" "Retrieve Vera data"
DATA='{"return":"0","ip":"'${VERA_IP}'"}'
SendResponse "${DATA}"
