#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/leds.inc
source /www/cgi-bin/ears.inc

ReadUrlParams
SILENT=${URLParam[silent]:-0}

KillProcess

if [ -e "${CNF_DATADIR}/Run/karotz.sleep" ]; then
	Log "[API]" "Waking Up"
	Leds ${CNF_BREEZE_COLOR} ${BLACK} 1
	EarsReset
	if [ ${SILENT} -eq 0 ]; then
		PlaySound /usr/karotz/res/sounds/karotz_allume.mp3
	fi
	rm ${CNF_DATADIR}/Run/karotz.sleep &>/dev/null
	rm ${CNF_DATADIR}/Run/karotz.time.sleep &>/dev/null
	DATA='{"return":"0","silent":"'${SILENT}'"}'
else
	Log "[API]" "Unable to waking Up, Karotz is already awake" 1
	DATA='{"return":"1","msg":"Unable to perform action, Karotz is already awake."}'
fi
SendResponse "${DATA}"
