#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc

Z_IP=""
if [ -e "${CNF_DATADIR}/Run/zibase.ip" ]; then
	Z_IP=$(cat ${CNF_DATADIR}/Run/zibase.ip)
fi
Log "[Home Automation]" "Retrieve Zibase data"
DATA='{"return":"0","ip":"'${Z_IP}'"}'
SendResponse "${DATA}"
