#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/ears.inc

Log "[Apps Clock]" "Clock Called"

CheckIsNotSleeping

ReadUrlParams
HOUR=${URLParam[hour]:-$((10#$(date +%H)))}

CheckMandatoryDirectory "${CNF_DATADIR}/Apps"
CheckMandatoryDirectory "${CNF_DATADIR}/Apps/Clock"
CheckMandatoryDirectory "${CNF_DATADIR}/Apps/Clock/Data"
CheckMandatoryDirectory "${CNF_DATADIR}/Apps/Clock/Data/${HOUR}"

KillProcess SOUNDS

NB=$(find ${CNF_DATADIR}/Apps/Clock/Data/${HOUR}/ -type f -name "*.mp3" 2>/dev/null | wc -l)
SOUND=$((RANDOM % NB + 1))
if [ ! -e "${CNF_DATADIR}/Apps/Clock/Data/${HOUR}/${SOUND}.mp3" ]; then
	Log "[Apps Clock]" "Sound not found" 1
	DATA='{"return":"1","msg":"File not found for hour '${HOUR}'."}'
else
	Log "[Apps Clock]" "Playing sound: "${CNF_DATADIR}/Apps/Clock/Data/${HOUR}/${SOUND}.mp3
	EarsReset
	PlaySound ${CNF_DATADIR}/Apps/Clock/Data/${HOUR}/${SOUND}.mp3 1
	DATA='{"return":"0","hour":"'${HOUR}'"}'
fi
SendResponse "${DATA}"
