#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/ears.inc

Log "[Apps Moods]" "Moods Called"

CheckIsNotSleeping

ReadUrlParams
MOOD=${URLParam[id]}
LANG=${URLParam[lang]:-fr}
if [ -z "${MOOD}" ]; then
	NB=$(find ${CNF_DATADIR}/Moods/${LANG}/ -type f -name "*.mp3" 2>/dev/null | wc -l)
	MOOD=$((RANDOM % NB + 1))
fi

CheckMandatoryDirectory "${CNF_DATADIR}/Moods"
CheckMandatoryDirectory "${CNF_DATADIR}/Moods/${LANG}"

KillProcess LED #TODO Why?
KillProcess SOUNDS

if [ ! -e "${CNF_DATADIR}/Moods/${LANG}/${MOOD}.mp3" ]; then
	Log "[Apps Moods]" "Mood not found ${MOOD} (${LANG})" 1
	DATA='{"return":"1","msg":"File not found for mood '${MOOD}' ('${LANG}')."}'
else
	Log "[Apps Moods]" "Mood ${MOOD} (${LANG}) played"
	#TODO Add a LEDs cinematic
	EarsReset
	PlaySound ${CNF_DATADIR}/Moods/${LANG}/${MOOD}.mp3 1
	DATA='{"return":"0","mood":"'${MOOD}'"}'
fi
SendResponse "${DATA}"
